{
 "title": "CoreDNS Recursor",
 "description": "A dashboard for the CoreDNS DNS server.",
 "tags": [
  "dns",
  "coredns"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(coredns_build_info,bosh_deployment)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(coredns_recursor_build_info{bosh_deployment=\"$deployment\"},instance)"
    }
   },
   {
    "name": "port",
    "label": "Port",
    "query": {
     "query": "label_values(coredns_recursor_resolvers_info{bosh_deployment=\"$deployment\", instance=~\"$instance\"},port)"
    }
   },
   {
    "name": "zone",
    "label": "Zone",
    "query": {
     "query": "label_values(coredns_recursor_resolvers_info{bosh_deployment=\"$deployment\", instance=~\"$instance\", port=~\"$port\"},zone)"
    }
   },
   {
    "name": "resolver",
    "label": "Resolver",
    "query": {
     "query": "label_values(coredns_recursor_resolvers_info{bosh_deployment=\"$deployment\", instance=~\"$instance\", port=~\"$port\", zone=~\"$zone\"},resolver)"
    }
   },
   {
    "name": "alias",
    "label": "Alias",
    "query": {
     "query": "label_values(coredns_recursor_aliases_info{bosh_deployment=\"$deployment\", instance=~\"$instance\", port=~\"$port\", zone=~\"$zone\", resolver=~\"$resolver\"},alias)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resolvers",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(coredns_recursor_resolvers_info{bosh_deployment=\"$deployment\", instance=~\"$instance\", port=~\"$port\", zone=~\"$zone\", resolver=~\"$resolver\"}) by (zone, resolver)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Aliases",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(coredns_recursor_aliases_info{bosh_deployment=\"$deployment\", instance=~\"$instance\", port=~\"$port\", zone=~\"$zone\", resolver=~\"$resolver\", alias=~\"$alias\"}) by (zone, resolver, alias, ttl)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Entries",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(coredns_recursor_aliases_entries_info{bosh_deployment=\"$deployment\", instance=~\"$instance\", port=~\"$port\", zone=~\"$zone\", resolver=~\"$resolver\", alias=~\"$alias\"}) by (zone, resolver, alias, type, entry)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Served Queries (/sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (zone, resolver, alias)(rate(coredns_recursor_query_served_count_total{bosh_deployment=\"$deployment\", instance=~\"$instance\", port=~\"$port\", zone=~\"$zone\", resolver=~\"$resolver\", alias=~\"$alias\"}[$__interval]))",
     "legendFormat": "{{alias}}.{{zone}}"
    }
   ]
  },
  {
   "title": "Omitted Queries (/sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (zone, resolver, alias, client_ip, reason)(rate(coredns_recursor_query_omitted_count_total{bosh_deployment=\"$deployment\", instance=~\"$instance\", port=~\"$port\", zone=~\"$zone\", resolver=~\"$resolver\", alias=~\"$alias\"}[$__interval]))",
     "legendFormat": "alias: '{{alias}}', zone: {{zone}}, client_ip: {{client_ip}} - {{reason}}"
    }
   ]
  },
  {
   "title": "Resolve Count (/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (zone, alias, resolver, host, result)(rate(coredns_recursor_resolve_count_total{bosh_deployment=\"$deployment\", instance=~\"$instance\", port=~\"$port\", zone=~\"$zone\", result=\"success\", alias=~\"$alias\"}[$__interval]))",
     "legendFormat": "{{alias}}.{{zone}} / {{host}} / {{result}}"
    }
   ]
  },
  {
   "title": "Resolve Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (zone, alias, resolver, host, result)(coredns_recursor_resolve_duration_ms{bosh_deployment=\"$deployment\", instance=~\"$instance\", port=~\"$port\", zone=~\"$zone\", result=\"success\", alias=~\"$alias\"})",
     "legendFormat": "{{alias}}.{{zone}} / {{host}} / {{result}}"
    }
   ]
  },
  {
   "title": "Resolved Ips (/sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(zone, alias, ip)(rate(coredns_recursor_resolve_ip_count_total{bosh_deployment=\"$deployment\",instance=~\"$instance\",port=~\"$port\",zone=~\"$zone\",alias=~\"$alias\"}[$__interval]))",
     "legendFormat": "{{alias}}.{{zone}} / {{ip}}"
    }
   ]
  },
  {
   "title": "Clients (/sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (client_ip)(rate(coredns_recursor_query_served_count_total{bosh_deployment=\"$deployment\", instance=~\"$instance\", port=~\"$port\", zone=~\"$zone\", resolver=~\"$resolver\", alias=~\"$alias\"}[$__interval])) ",
     "legendFormat": "{{client_ip}}"
    }
   ]
  },
  {
   "title": "Resolved Ips for Clients (/sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (zone, alias, client_ip)(rate(coredns_recursor_query_served_count_total{bosh_deployment=\"$deployment\", instance=~\"$instance\", port=~\"$port\", zone=~\"$zone\", resolver=~\"$resolver\", alias=~\"$alias\"}[$__interval]))",
     "legendFormat": "{{alias}}.{{zone}} cli={{client_ip}}"
    }
   ]
  }
 ]
}